### ISSUE TITLE
Paypal cart

### ISSUE THREAD

**Issue by kostaslgr** [G3N-es/G3nshop-for-Bludit#3]
Hello there!

I would like to ask whether it is feasible, after pressing the paypal button to checkout to be able to choose the language of the paypal website.

I have also noticed that there is 2 Euro shipping cost. How can i configure the shipping cost?

Also, could you please make it easy to change the green color on the Featured part of the first page?

This plugin is amazing.

**Comment by kolim4801** [comment]
I fixed the issue - for those who had the same problem - g3nshop from bludit has a secret value in their Paypal add to cart buttons - simply add the shipping value to 0.00 instead of 1.00 in products php.

**Comment by G3N-es** [comment]
@kolim4801 @kostaslgr 

It is not possible to set the language that Paypal will take.

There is a new update (v2 compatible with Bludit 3.14) that solves the shipping cost problem and adds new features.
Among them create custom CSS, which allows you to change the color to Featured.
